name             'typo_cookbook'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures typo_cookbook'
long_description 'Installs/Configures typo_cookbook'
version          '0.1.0'

depends 'dd_pcp_ext'
depends 'dd_pcp_int'